# Generated by Django 4.0.2 on 2022-02-03 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lead', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='developers',
            field=models.ManyToManyField(blank=True, to='lead.Developer'),
        ),
    ]
